# Data Cleaning with Pandas

## Detect Missing data Rows

In [23]:
import pandas as pd
import numpy as np

data = {'Name': ['Alice', 'Bob', 'Charlie', None],
        'Age': [25, 30, 'NaN', 35],
        'City': ['New York', 'Los Angeles', 'Chicago', ' ']}

df = pd.DataFrame(data)

print(df)

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie  NaN      Chicago
3     None   35

In [24]:
df.isna()

    Name    Age   City
0  False  False  False
1  False  False  False
2  False  False  False
3   True  False  False

In [25]:
df = df.replace([" ", "NaN"], None)
df.isna()

    Name    Age   City
0  False  False  False
1  False  False  False
2  False   True  False
3   True  False   True

In [26]:
df.isna().sum()

Name    1
Age     1
City    1
dtype: int64

## Remove Missing Values

In [28]:
new_df = df.dropna()
print(new_df)

    Name Age         City
0  Alice  25     New York
1    Bob  30  Los Angeles

In [21]:
print(df)

      Name   Age         City
0    Alice    25     New York
1      Bob    30  Los Angeles
2  Charlie  None      Chicago
3     None    35         None

In [22]:
df.dropna(inplace = True)
print(df)

    Name Age         City
0  Alice  25     New York
1    Bob  30  Los Angeles

## Replace missing data

In [29]:
import pandas as pd

data = {'Name': ['Alice', 'Bob', 'Charlie', None],
        'Age': [25, 30, None, 35],
        'City': ['New York', 'Los Angeles', 'Chicago', 'Houston']}

df = pd.DataFrame(data)

print(df)

      Name   Age         City
0    Alice  25.0     New York
1      Bob  30.0  Los Angeles
2  Charlie   NaN      Chicago
3     None  35.0      Houston

In [30]:
new_df = df.fillna(100)
print(new_df)

      Name    Age         City
0    Alice   25.0     New York
1      Bob   30.0  Los Angeles
2  Charlie  100.0      Chicago
3      100   35.0      Houston

In [31]:
df['Age'] = df['Age'].fillna(200)
print(df)

# df['Age'].fillna(200, inplace = True) # does not work in Pandas 3.0
# print(df)

      Name    Age         City
0    Alice   25.0     New York
1      Bob   30.0  Los Angeles
2  Charlie  200.0      Chicago
3     None   35.0      Houston

In [32]:
import pandas as pd

data = {'Name': ['Alice', 'Bob', 'Charlie', None],
        'Age': [25, 30, None, 35],
        'City': ['New York', 'Los Angeles', 'Chicago', 'Houston']}

df = pd.DataFrame(data)

# df['Age'] = df['Age'].fillna(df['Age'].mean())
df['Age'] = df['Age'].fillna(df['Age'].median())

print(df)

      Name   Age         City
0    Alice  25.0     New York
1      Bob  30.0  Los Angeles
2  Charlie  30.0      Chicago
3     None  35.0      Houston

## Convert Correct Data Format

In [37]:
import pandas as pd

data = {
  "Date": ['2020/12/01', '2020/12/02', '20201226'],
  "duration": [50, 40, 45]
}

df = pd.DataFrame(data, index = ['day1', 'day2', 'day3'])
print(df)

            Date  duration
day1  2020/12/01        50
day2  2020/12/02        40
day3    20201226        45

In [40]:
df['Date'] = pd.to_datetime(df['Date'], format='mixed') # avoids trying to apply a single, specific format to the entire dataset. 
# format can significantly improve performance when converting large datasets, as pandas doesn't need to infer the pattern.

print(df)

           Date  duration
day1 2020-12-01        50
day2 2020-12-02        40
day3 2020-12-26        45

In [41]:
import pandas as pd

data = {
  "Date": ['2020/12/01', '2020/12/02' , '20201226'],
  "duration": [50, 40, 45]
}

df = pd.DataFrame(data, index = ['day1', 'day2', 'day3'])

df['Date'] = pd.to_datetime(df['Date'], format='mixed')

print(df)

df['Date'] = df['Date'].dt.strftime('%m/%d/%Y')
# dt.: operations performed on a datetime type column
# strftime: Convert the date to a string according to the specified format.

print(df)

           Date  duration
day1 2020-12-01        50
day2 2020-12-02        40
day3 2020-12-26        45
            Date  duration
day1  12/01/2020        50
day2  12/02/2020        40
day3  12/26/2020        45

In [30]:
import pandas as pd

df = pd.DataFrame({
    "A": ["1", "2", "3", "bad", None]
})

print(df)

df['A'] = pd.to_numeric(df['A'], errors="coerce")
# If pandas cannot convert a value to the desired type, it will replace it with a “missing value” (NaN) instead of raising an error.

print(df)

      A
0     1
1     2
2     3
3   bad
4  None
     A
0  1.0
1  2.0
2  3.0
3  NaN
4  NaN

In [45]:
import pandas as pd

df = pd.DataFrame({
    "Major": ["CS", "cs", "Computer Science", "CS", "computer science"]
})

print(df)

df["Major"] = df["Major"].str.lower()
print(df)

              Major
0                CS
1                cs
2  Computer Science
3                CS
4  computer science
              Major
0                cs
1                cs
2  computer science
3                cs
4  computer science

In [44]:
major_map = {
    "cs": "Computer Science",
    "computer science": "Computer Science"
}

df["Major"] = df["Major"].replace(major_map)
print(df)

              Major
0  Computer Science
1  Computer Science
2  Computer Science
3  Computer Science
4  Computer Science

In [46]:
df["Major"] = df["Major"].replace(['cs', 'computer science'], 'Computer Science')
print(df)

              Major
0  Computer Science
1  Computer Science
2  Computer Science
3  Computer Science
4  Computer Science

## Outliers

In [47]:
import pandas as pd

person = {
  "name": ['Google', 'Meta', 'Apple'],
  "age": [50, 40, 12345]
}

df = pd.DataFrame(person)

df.loc[2, 'age'] = 30

print(df)

     name  age
0  Google   50
1    Meta   40
2   Apple   30

In [48]:
import pandas as pd

person = {
  "name": ['Google', 'Meta', 'Apple'],
  "age": [50, 40, 12345]
}

df = pd.DataFrame(person)

for x in df.index:
  if df.loc[x, "age"] > 120:
    df.loc[x, "age"] = 120

print(df)

     name  age
0  Google   50
1    Meta   40
2   Apple  120

In [33]:
import pandas as pd

person = {
  "name": ['Google', 'Meta', 'Apple'],
  "age": [50, 40, 12345]
}

df = pd.DataFrame(person)

for x in df.index:
  if df.loc[x, "age"] > 120:
      df.drop(x, inplace = True)

print(df)

     name  age
0  Google   50
1    Meta   40

In [53]:
import pandas as pd

person = {
  "Name": ['A', 'B', 'C', 'D', 'E', 'F', 'G'],
  "Age": [10, 20, 24, 26, 30, 32, 90]
}

df = pd.DataFrame(person)

Q1 = df["Age"].quantile(0.25)
Q3 = df["Age"].quantile(0.75)

IQR = Q3 - Q1

outliers = df[
    (df["Age"] < Q1 - 1.5 * IQR) |
    (df["Age"] > Q3 + 1.5 * IQR)
]
print(outliers)

df.loc[6, "Age"] = int(Q3 + 1.5 * IQR)
print(df)

  Name  Age
6    G   90
  Name  Age
0    A   10
1    B   20
2    C   24
3    D   26
4    E   30
5    F   32
6    G   44

## Remove Duplicate

In [54]:
import pandas as pd

person = {
  "name": ['Google', 'Meta', 'Apple', 'Google'],
  "age": [50, 40, 12345, 50]
}
df = pd.DataFrame(person)

print(df.duplicated())

0    False
1    False
2    False
3     True
dtype: bool

In [59]:
import pandas as pd

person = {
  "name": ['Google', 'Meta', 'Apple', 'Google'],
  "age": [50, 40, 12345, 50]
}
df = pd.DataFrame(person)

df.drop_duplicates(inplace = True)
#df.drop_duplicates(subset=["name"], inplace = True)
print(df)

     name    age
0  Google     50
1    Meta     40
2   Apple  12345

In [60]:
import pandas as pd

data = {
    "Name": ["Alice", "Bob", "Charlie", "Alice", "David", "Eve", "Frank"],
    "Age": [25, 30, None, 25, 150, 28, None],
    "Salary": [50000, None, 60000, 50000, 7000000, 52000, 58000],
    "Department": ["IT", "HR", "IT", "IT", "Finance", None, "HR"]
}

df = pd.DataFrame(data)
df.to_csv('Staff.csv', index = None)
print(df)

      Name    Age     Salary Department
0    Alice   25.0    50000.0         IT
1      Bob   30.0        NaN         HR
2  Charlie    NaN    60000.0         IT
3    Alice   25.0    50000.0         IT
4    David  150.0  7000000.0    Finance
5      Eve   28.0    52000.0       None
6    Frank    NaN    58000.0         HR

## In-Class Exercise

In [61]:
import pandas as pd

df = pd.read_csv('Staff.csv')

# Handle missing values
df["Age"] = df["Age"].fillna(30)
df["Salary"] = df["Salary"].fillna(df["Salary"].mean())

# Remove duplicates
df = df.drop_duplicates()

# Handle outliers
median_salary = df["Salary"].median()
df.loc[df["Salary"] > 200000, "Salary"] = median_salary
df.loc[df["Age"] > 120, 'Age'] = 120

# Standardize data types
df["Age"] = df["Age"].astype("Int64")

df.to_csv('clean.csv', index = None)

print(df)
print(df.dtypes)

      Name  Age   Salary Department
0    Alice   25  50000.0         IT
1      Bob   30  59000.0         HR
2  Charlie   30  60000.0         IT
4    David  120  59000.0    Finance
5      Eve   28  52000.0        NaN
6    Frank   30  58000.0         HR
Name           object
Age             Int64
Salary        float64
Department     object
dtype: object